name: achronon
favicon: null
layout_spectrum: 0.3020275814924389
typography_spectrum: 0.9026462908368558
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.909201645758003
  lightness: 0.9709311311598867
  saturation: 0.8152413847856224
  rhythmicContrast: 0.9926855929661542
purpose: []
