name: achronon
favicon: null
layout_spectrum: 0.3020275814924389
typography_spectrum: 0.9026462908368558
title: A time-free quest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feda3b'
    - '#ec9d00'
    - '#c9c9c9'
    - '#757575'
    - '#3a3a3a'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
